apiVersion: v1
kind: Service
metadata:
  name: data-retrival-service
spec:
  type: LoadBalancer
  selector:
    app: data-retrival-service
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30422
