name: data-retrival-service

on:
  push:
    branches: [ main ]
    paths: 
      - "data-retrival-service/**"
      - ".github/workflows/data-retrival-service.yaml"
  pull_request:
    branches: [ main ]
    paths: 
      - "data-retrival-service/**"
      - ".github/workflows/data-retrival-service.yaml"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        cd data-retrival-service
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: kartheekj59/data-retrival-service
        tags: latest
        registry: docker.io
        directory: data-retrival-service
        dockerfile: data-retrival-service/Dockerfile
        username: kartheekj59
        password: 372d0b75-b8a1-4514-a294-2ff61c46fb74
